version: '3.7'

services:

 my-app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
        - ./letsencrypt:/etc/letsencrypt
    ports:
        - "80:80"
        - "443:443"
